# Toolchain for this project. Run `rokit install` to get these versions.
[tools]
rojo = "rojo-rbx/rojo@7.7.0"
wally = "upliftgames/wally@0.3.2"
selene = "kampfkarren/selene@0.31.0"
stylua = "johnnymorganz/stylua@2.5.2"
lune = "lune-org/lune@0.10.4"
luau-lsp = "johnnymorganz/luau-lsp@1.69.0"
